// Export all hooks from a single file for easier importing
export { useUser } from './useUser';
export { useAuth } from './useAuth';
export { useProfile } from './useProfile';
export { useQuran } from './useQuran';
export { useHadith } from './useHadith';
export { useDua } from './useDua';
export { useFavorites } from './useFavorites';
export { useReadingProgress } from './useReadingProgress';
export { usePrayerTimes } from './usePrayerTimes';
export { useSearch } from './useSearch';
export { useNotifications } from './useNotifications';
export { useTheme } from './useTheme';
export { useGeolocation } from './useGeolocation';
export { useVideos } from './useVideos';
export { useAI } from './useAI';
export { useOnline } from './useOnline';
export { useDebounce } from './useDebounce';
export { useLocalStorage } from './useLocalStorage';
