-- Historical migration version retained for Supabase migration history reconciliation.
-- No-op: the original RLS/triggers/storage migration was archived after being
-- superseded by the canonical guarded migration chain in this directory.
