-- Source-verified tawasheeh expansion.
-- Every audio URL points to an Internet Archive item marked Public Domain on its source page.
-- Keep source_url and license in metadata so the UI and reviewers can audit provenance.

WITH categories AS (
  SELECT id, slug FROM public.tawasheeh_categories
  WHERE slug IN ('religious', 'prophetic', 'supplications')
), tracks (title_ar, title_en, slug, artist_ar, artist_en, category_slug, audio_url, duration, featured, metadata) AS (
  VALUES
    ('ببابك', 'At Your Door', 'bebabak-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'supplications', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%A8%D8%A8%D8%A7%D8%A8%D9%83.mp3', 360, true, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('النفس تشكو', 'The Soul Complains', 'al-nafs-tashku-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'supplications', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%A7%D9%84%D9%86%D9%81%D8%B3%20%D8%AA%D8%B4%D9%83%D9%88.mp3', 360, true, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('رسول الله', 'Messenger of Allah', 'rasool-allah-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'prophetic', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%B1%D8%B3%D9%88%D9%84%20%D8%A7%D9%84%D9%84%D9%87.mp3', 360, true, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('سبحانك اللهم', 'Glory Be to You, O Allah', 'subhanaka-allahumma-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'religious', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%B3%D8%A8%D8%AD%D8%A7%D9%86%D9%83%20%D8%A7%D9%84%D9%84%D9%87%D9%85.mp3', 240, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('إلهي', 'My Lord', 'ilahi-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'supplications', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%A5%D9%84%D9%87%D9%8A.mp3', 240, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('مناجاة', 'Private Supplication', 'munajat-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'supplications', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D9%85%D9%86%D8%A7%D8%AC%D8%A7%D8%A9.mp3', 300, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('يا رب', 'O Lord', 'ya-rabb-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'supplications', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D9%8A%D8%A7%20%D8%B1%D8%A8.mp3', 300, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('يا نور', 'O Light', 'ya-noor-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'religious', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D9%8A%D8%A7%20%D9%86%D9%88%D8%B1.mp3', 300, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('حمداً لك', 'Praise Be to You', 'hamdan-lak-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'religious', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%AD%D9%85%D8%AF%D8%A7%20%D9%84%D9%83.mp3', 300, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('خير البرية', 'Best of Creation', 'khayr-al-bariyya-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'prophetic', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%AE%D9%8A%D8%B1%D8%A7%D9%84%D8%A8%D8%B1%D9%8A%D8%A9.MP3', 300, true, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('مولد الرسول', 'The Prophet''s Birth', 'mawlid-al-rasool-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'prophetic', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D9%85%D9%88%D9%84%D8%AF%20%D8%A7%D9%84%D8%B1%D8%B3%D9%88%D9%84.mp3', 300, false, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb),
    ('الصلاة على الحبيب', 'Blessings Upon the Beloved', 'salat-ala-al-habib-naqshbandi', 'الشيخ سيد النقشبندي', 'Sheikh Sayed Al-Naqshbandi', 'prophetic', 'https://archive.org/download/Sama3almelouk_yahoo_20160525/%D8%A7%D9%84%D8%B5%D9%84%D8%A7%D8%A9%20%D8%B9%D9%84%D9%89%20%D8%A7%D9%84%D8%AD%D8%A8%D9%8A%D8%A8.mp3', 300, true, '{"source_url":"https://archive.org/details/Sama3almelouk_yahoo_20160525","source_item":"Sama3almelouk_yahoo_20160525","license":"Public Domain Mark 1.0","format":"MP3"}'::jsonb)
)
INSERT INTO public.tawasheeh (title_ar, title_en, slug, artist_ar, artist_en, category_id, audio_url, duration, featured, published, metadata)
SELECT t.title_ar, t.title_en, t.slug, t.artist_ar, t.artist_en, c.id, t.audio_url, t.duration, t.featured, true, t.metadata
FROM tracks t JOIN categories c ON c.slug = t.category_slug
ON CONFLICT (slug) DO UPDATE SET audio_url = EXCLUDED.audio_url, duration = EXCLUDED.duration, featured = EXCLUDED.featured, published = true, metadata = EXCLUDED.metadata, updated_at = now();

-- Existing seed rows without a verified direct audio file remain unpublished
-- by the API until a source URL is reviewed and added in a later migration.
