-- Curated first tranche of source-indexed companion biographies.
-- The catalogue is intentionally expandable; it must not claim to enumerate every Companion.
-- These guards keep the migration valid on a clean baseline as well as on production,
-- where the compatibility migration may already have created the columns.
ALTER TABLE public.companions ADD COLUMN IF NOT EXISTS birth_place_ar text;
ALTER TABLE public.companions ADD COLUMN IF NOT EXISTS death_place_ar text;
ALTER TABLE public.companions ADD COLUMN IF NOT EXISTS death_year text;

INSERT INTO public.companions
  (id, name_ar, name_en, slug, bio_ar, bio_en, category, birth_place_ar, death_place_ar, death_year, order_num, published, metadata)
VALUES
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1101', 'خديجة بنت خويلد', 'Khadijah bint Khuwaylid', 'khadijah-bint-khuwaylid', 'أم المؤمنين خديجة بنت خويلد رضي الله عنها، زوج النبي ﷺ وأول من آمن به وصدّقه عند بدء الوحي. عُرفت برجاحة العقل والكرم وحسن المعاشرة، وكانت سندًا للنبي في أصعب أعوام الدعوة المكية. لا تُفهم سيرتها في المنصة على أنها مجرد قصة عائلية، بل نموذج للإيمان المبكر، وبذل المال، وتثبيت صاحب الرسالة مع حفظ مقام النبوة.', 'Khadijah bint Khuwaylid, Mother of the Believers and the first person to believe in the Prophet ﷺ.', 'أمهات المؤمنين', 'مكة المكرمة', 'مكة المكرمة', 'قبل الهجرة', 7, true, '{"content_status":"primary_indexed","references":[{"title_ar":"صحيح البخاري — بدء الوحي وقصة خديجة رضي الله عنها","source_type":"hadith","url":"https://sunnah.com/bukhari:3","locator_ar":"حديث بدء الوحي","note_ar":"يُرجع إلى النص الكامل وسياق الرواية."},{"title_ar":"صحيح البخاري — فضائل خديجة رضي الله عنها","source_type":"hadith","url":"https://sunnah.com/bukhari/61","locator_ar":"كتاب المناقب","note_ar":"الفهرس العام يحتاج إلى تحديد رقم الحديث عند الاقتباس."}]}'::jsonb),
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1102', 'عائشة بنت أبي بكر', 'Aishah bint Abi Bakr', 'aisha-bint-abi-bakr', 'أم المؤمنين عائشة رضي الله عنها، زوج النبي ﷺ وابنة أبي بكر الصديق. كانت من أعلم الصحابة بالحديث والفقه وأحوال بيت النبوة، ورجع إليها كبار الصحابة في مسائل العلم. تحفظ سيرتها معاني طلب العلم، ودقة النقل، والرجوع إلى الدليل، كما تتضمن حادثة الإفك التي برأها الله منها بآيات من سورة النور، ولذلك ينبغي عرضها بتوقير وبالرجوع إلى النص القرآني والرواية الصحيحة.', 'Aishah bint Abi Bakr, Mother of the Believers and a major early authority in hadith and Islamic knowledge.', 'أمهات المؤمنين', 'مكة المكرمة', 'المدينة المنورة', '58هـ', 8, true, '{"content_status":"primary_indexed","references":[{"title_ar":"القرآن الكريم — آيات حادثة الإفك","source_type":"quran","url":"https://quran.com/24/11-26","locator_ar":"سورة النور 11–26","note_ar":"تُقرأ الآيات كاملة مع سياقها، ولا يُختزل الحدث في عبارات عاطفية."},{"title_ar":"صحيح البخاري — رواية الإفك","source_type":"hadith","url":"https://sunnah.com/bukhari:4141","locator_ar":"حديث الإفك","note_ar":"يُراجع النص الكامل قبل الاستشهاد."}]}'::jsonb),
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1103', 'حمزة بن عبد المطلب', 'Hamzah ibn Abd al-Muttalib', 'hamzah-ibn-abd-al-muttalib', 'حمزة بن عبد المطلب رضي الله عنه عم النبي ﷺ وأخوه من الرضاعة، ومن السابقين إلى الإسلام. جمع بين قوة الشخصية ونصرة الحق، وكان حضوره حماية للمؤمنين في مكة. استشهد في غزوة أُحد، وتُعرض سيرته في إطار الشجاعة المنضبطة ونصرة المظلوم، مع تجنب القصص المتأخرة التي لا يثبت سندها.', 'Hamzah ibn Abd al-Muttalib, the Prophet’s uncle and an early Muslim who was martyred at Uhud.', 'آل بيت النبي والصحابة', 'مكة المكرمة', 'جبل أُحد', '3هـ', 9, true, '{"content_status":"source_indexed","references":[{"title_ar":"صحيح البخاري — فضائل أصحاب النبي ﷺ","source_type":"hadith","url":"https://sunnah.com/bukhari/62","locator_ar":"كتاب المناقب","note_ar":"يجب تحديد الحديث بعينه عند النقل."},{"title_ar":"القرآن الكريم — منزلة الشهداء","source_type":"quran","url":"https://quran.com/3/169","locator_ar":"آل عمران 169","note_ar":"الآية أصل عام في حياة الشهداء عند ربهم، وليست سردًا تفصيليًا لكل أحداث أُحد."}]}'::jsonb),
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1104', 'زيد بن ثابت', 'Zayd ibn Thabit', 'zayd-ibn-thabit', 'زيد بن ثابت رضي الله عنه من الأنصار، ومن كتّاب الوحي، وكان من أهل العلم والقراءة والفرائض. برز دوره في جمع القرآن في خلافة أبي بكر ثم في نسخ المصاحف في خلافة عثمان رضي الله عنهما، كما كان مرجعًا في العلم بالقراءة والمواريث. تُظهر سيرته أن خدمة الوحي تحتاج إلى حفظ وإتقان وعمل مؤسسي جماعي، لا إلى الاعتماد على الذاكرة المجردة وحدها.', 'Zayd ibn Thabit, an Ansari scribe of revelation and a leading authority in Quranic compilation and inheritance.', 'الأنصار وكتّاب الوحي', 'المدينة المنورة', 'المدينة المنورة', '45هـ', 10, true, '{"content_status":"primary_indexed","references":[{"title_ar":"صحيح البخاري — جمع القرآن","source_type":"hadith","url":"https://sunnah.com/bukhari:4986","locator_ar":"حديث جمع القرآن في عهد أبي بكر","note_ar":"يُقرأ الحديث كاملًا لمعرفة التسلسل التاريخي."},{"title_ar":"صحيح البخاري — كتابة المصحف في عهد عثمان","source_type":"hadith","url":"https://sunnah.com/bukhari/61","locator_ar":"كتاب المناقب","note_ar":"تُراجع الرواية المحددة قبل إدراج اقتباس مباشر."}]}'::jsonb),
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1105', 'عبد الله بن عباس', 'Abdullah ibn Abbas', 'abdullah-ibn-abbas', 'عبد الله بن عباس رضي الله عنهما ابن عم النبي ﷺ، ومن كبار علماء الصحابة والمفسرين. لازم النبي في صغره، ودعا له النبي بالفقه في الدين والعلم بالتأويل، ثم أصبح مرجعًا في تفسير القرآن واللغة والفقه. تعلمنا سيرته أن صغر السن لا يمنع بلوغ العلم، وأن الفهم يحتاج إلى ملازمة العلماء، وحسن السؤال، وحفظ النص مع فهم دلالته.', 'Abdullah ibn Abbas, a Companion known for Quranic knowledge, tafsir, and jurisprudence.', 'العلماء والمفسرون من الصحابة', 'مكة المكرمة', 'الطائف', '68هـ', 11, true, '{"content_status":"primary_indexed","references":[{"title_ar":"صحيح البخاري — الدعاء لابن عباس بالفقه","source_type":"hadith","url":"https://sunnah.com/bukhari:75","locator_ar":"كتاب العلم","note_ar":"يُراجع لفظ الحديث ورقمه في الطبعة المستخدمة."},{"title_ar":"صحيح البخاري — فضائل ابن عباس","source_type":"hadith","url":"https://sunnah.com/bukhari/62","locator_ar":"كتاب المناقب","note_ar":"الفهرس العام لا يغني عن تحديد الرواية."}]}'::jsonb),
  ('6a33a3f0-3f6b-4a6c-8b21-2f0a5d0e1106', 'أبو ذر الغفاري', 'Abu Dharr al-Ghifari', 'abu-dharr-al-ghifari', 'أبو ذر الغفاري رضي الله عنه من السابقين إلى الإسلام، عُرف بصدق اللهجة والزهد والجرأة في إعلان التوحيد. تروي المصادر الصحيحة قصة بحثه عن النبي ﷺ ووصوله إلى مكة ثم إسلامه وإعلانه الشهادة رغم الأذى. تعرض سيرته قيمة الصدق والثبات، مع التنبيه إلى أن الزهد لا يعني ترك المسؤولية أو تحريم الطيبات التي أباحها الله.', 'Abu Dharr al-Ghifari, an early Companion known for truthfulness, courage, and ascetic character.', 'السابقون إلى الإسلام', 'نجد/غفار', 'الربذة', '32هـ', 12, true, '{"content_status":"primary_indexed","references":[{"title_ar":"صحيح البخاري — قصة إسلام أبي ذر","source_type":"hadith","url":"https://sunnah.com/bukhari:3522","locator_ar":"كتاب المناقب","note_ar":"يُقرأ الحديث مع الروايات المتصلة به."},{"title_ar":"تنبيه تربوي حول الزهد","source_type":"editorial","locator_ar":"لا تُنسب العبارات التربوية إلى أبي ذر إلا بمصدر محدد","note_ar":"التلخيص التعليمي ليس حديثًا ولا نصًا تاريخيًا مستقلًا."}]}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name_ar = excluded.name_ar,
  name_en = excluded.name_en,
  bio_ar = excluded.bio_ar,
  bio_en = excluded.bio_en,
  category = excluded.category,
  birth_place_ar = excluded.birth_place_ar,
  death_place_ar = excluded.death_place_ar,
  death_year = excluded.death_year,
  order_num = excluded.order_num,
  published = excluded.published,
  metadata = excluded.metadata,
  updated_at = now();

INSERT INTO public.companion_stories (id, companion_id, title_ar, title_en, content_ar, content_en, story_type, order_num)
VALUES
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2201', (select id from public.companions where slug='khadijah-bint-khuwaylid' limit 1), 'ثباتها عند بدء الوحي', 'Steadfastness at the Beginning of Revelation', 'لما رجع النبي ﷺ من غار حراء خائفًا مما رأى، لم تواجه خديجة رضي الله عنها الخبر بالسخرية أو الاضطراب، بل طمأنته وذكّرته بخصاله التي يعرفها الناس فيه: صلة الرحم، وصدق الحديث، وحمل الكَلّ، وإغاثة الملهوف. ثم أخذته إلى ورقة بن نوفل لطلب التثبت من الأمر. في هذا الموقف تظهر فطنة خديجة وحسن إدارتها للأزمة، مع بقاء الوحي والنبوة أمرًا إلهيًا لا يثبت بمجرد الانطباع البشري.', 'Khadijah offered reassurance and sought informed confirmation after the first revelation.', 'الإيمان والنصرة', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2202', (select id from public.companions where slug='khadijah-bint-khuwaylid' limit 1), 'الإنفاق في نصرة الدعوة', 'Supporting the Mission', 'كانت خديجة رضي الله عنها شريكة حياة للنبي ﷺ في المرحلة المكية، وبذلت من مكانتها ومالها ووقتها ما أعان على احتمال أذى قريش. لا يصح تحويل هذه المعاني إلى أرقام أو حكايات تفصيلية بلا سند، لكن الثابت في الجملة أن الصحابة الأوائل بذلوا ما يستطيعون لنصرة الحق، وأن خديجة كانت من أعظم من ثبت وواسَى رسول الله ﷺ.', 'Khadijah supported the early Muslim community with her standing, wealth, and steadfast companionship.', 'البذل والنصرة', 2),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2203', (select id from public.companions where slug='aisha-bint-abi-bakr' limit 1), 'العلم والرواية', 'Knowledge and Transmission', 'تُظهر سيرة عائشة رضي الله عنها أن بيت النبوة كان مدرسة علمية، فقد نقلت أحوال النبي ﷺ في العبادة والمعاشرة والفتوى، وسألها الصحابة والتابعون عن مسائل لم يطلع عليها غيرها. ومنهجها يعلّم الباحث أن الرواية لا تُؤخذ من الذاكرة العامة فقط، بل تُقارن بالألفاظ والأسانيد وموضوع السؤال وسياقه.', 'Aishah transmitted knowledge from the Prophetic household and became a major authority for later Muslims.', 'العلم والحديث', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2204', (select id from public.companions where slug='aisha-bint-abi-bakr' limit 1), 'حادثة الإفك والبراءة', 'The Incident of the Slander', 'كانت حادثة الإفك ابتلاءً شديدًا لأم المؤمنين عائشة رضي الله عنها وللمجتمع المسلم. حفظ القرآن أصل القصة وبرأها، وعلّم المؤمنين ألا يتلقوا الأخبار بلا تثبت، وألا يشيعوا الفاحشة، وأن يردوا الأمر إلى الدليل. عند دراسة هذا الحدث يجب قراءة آيات سورة النور كاملة، ثم مراجعة حديث الإفك الصحيح، وعدم إضافة مشاهد درامية لا يثبتها المصدر.', 'The Quranic account teaches verification, restraint, and rejection of rumor.', 'ابتلاء وتثبيت', 2),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2205', (select id from public.companions where slug='hamzah-ibn-abd-al-muttalib' limit 1), 'نصرة النبي في مكة', 'Defending the Prophet in Makkah', 'كان إسلام حمزة رضي الله عنه من الأحداث التي قوّت جانب المسلمين في مكة، إذ كان صاحب مكانة وشجاعة. ومع ذلك، فالنصرة في السيرة ليست مجرد قوة جسدية؛ بل التزام بالعقيدة وحماية للرسالة واحتمال للتبعات. تعرض هذه الصفحة الموقف العام مع ترك التفاصيل التي تحتاج إلى إسناد مستقل.', 'Hamzah’s acceptance of Islam strengthened the vulnerable early Muslim community in Makkah.', 'النصرة والشجاعة', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2206', (select id from public.companions where slug='hamzah-ibn-abd-al-muttalib' limit 1), 'الشهادة في أُحد', 'Martyrdom at Uhud', 'استشهد حمزة رضي الله عنه في أُحد، وكانت شهادته من مصائب المسلمين في ذلك اليوم. لا تُستكمل دراسة أُحد بذكر الشجاعة وحدها، بل تُقرأ معها آيات آل عمران التي تناولت أسباب الابتلاء والتثبيت ومراجعة الأخطاء. وهكذا تتحول السيرة من حكاية بطولة إلى درس في الإيمان والصبر والمسؤولية.', 'His martyrdom at Uhud is studied alongside the Quranic lessons of the battle.', 'السيرة والشهادة', 2),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2207', (select id from public.companions where slug='zayd-ibn-thabit' limit 1), 'جمع القرآن بعد وفاة النبي ﷺ', 'The Compilation of the Quran', 'بعد استشهاد عدد من القراء، ظهرت الحاجة إلى جمع القرآن في مصحف جامع، فاختير زيد بن ثابت رضي الله عنه لما عُرف به من كتابة الوحي والعلم والأمانة. تذكر الرواية الصحيحة أنه جمعه من المواد المكتوبة ومن صدور الرجال، ثم بقي المصحف عند أبي بكر ثم عمر ثم حفصة رضي الله عنهم. هذه الحادثة نموذج للتوثيق الجماعي وحفظ النص.', 'Zayd helped compile the Quran through a careful collective preservation process.', 'خدمة القرآن', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2208', (select id from public.companions where slug='zayd-ibn-thabit' limit 1), 'نسخ المصاحف في عهد عثمان', 'The Uthmanic Manuscripts', 'لما اتسعت البلاد وظهر اختلاف الناس في وجوه القراءة، شارك زيد بن ثابت رضي الله عنه في عمل نسخ المصاحف على مصحف إمام، مع مراعاة لغة قريش عند الاختلاف. ينبغي عرض هذا الحدث في إطار حفظ وحدة الأمة والنص، مع احترام مباحث القراءات وعدم تحويل التلخيص إلى حكم تفصيلي في علوم المصحف.', 'Zayd participated in preparing standardized manuscripts during the caliphate of Uthman.', 'العلم والمؤسسة', 2),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2209', (select id from public.companions where slug='abdullah-ibn-abbas' limit 1), 'الدعاء بالعلم والفقه', 'A Prayer for Knowledge', 'دعا النبي ﷺ لابن عباس رضي الله عنهما بالفقه في الدين والعلم بالتأويل، فكان ذلك باعثًا على اجتهاده في طلب العلم وملازمة أهل الخبرة. لا يعني هذا أن العلم يأتي بالدعاء وحده؛ فقد جمع ابن عباس بين الدعاء والتعلم والسؤال والحفظ، ولذلك صار مثالًا للطالب الذي يحول الموهبة إلى مشروع علمي.', 'The Prophetic prayer was joined with sustained study, questioning, and careful transmission.', 'التعلم والفقه', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2210', (select id from public.companions where slug='abdullah-ibn-abbas' limit 1), 'منهج الباحث في التفسير', 'A Research Method for Tafsir', 'تُقرأ آثار ابن عباس في التفسير مع التمييز بين ما ثبت عنه وما نُسب إليه في الكتب المتأخرة. ومن المنهج العلمي أن يُذكر نص الآية، ثم تُراجع الأحاديث والآثار وأقوال أئمة التفسير، وألا يُقدّم تفسير واحد في موضع الخلاف على أنه إجماع. هذا المنهج يجعل السيرة نافعة للطالب في البحث لا مجرد مادة للحفظ.', 'Reports attributed to Ibn Abbas should be assessed by their chains and scholarly context.', 'منهج البحث', 2),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2211', (select id from public.companions where slug='abu-dharr-al-ghifari' limit 1), 'رحلة البحث عن التوحيد', 'The Search for Tawhid', 'تروي رواية صحيحة قصة أبي ذر رضي الله عنه حين سمع بظهور النبي ﷺ، فأرسل أخاه ثم خرج بنفسه إلى مكة، وتثبت من الأمر حتى لقي النبي وأسلم. تعرض القصة صدق الفطرة وحرص طالب الحق على التحقق، كما تذكّر بأن الشجاعة لا تلغي الحكمة؛ فقد أوصاه النبي أولًا بالكتمان ثم عاد فأعلن إسلامه باختياره.', 'The authentic report presents Abu Dharr’s search, verification, and courage in accepting Islam.', 'طلب الحق', 1),
  ('7b44b4f1-4f7c-4b7d-9c32-3f1b6e1f2212', (select id from public.companions where slug='abu-dharr-al-ghifari' limit 1), 'الصدق والزهد مع حفظ الميزان', 'Truthfulness and Asceticism', 'اشتهر أبو ذر رضي الله عنه بصدق اللهجة والزهد، لكن دراسة الزهد تحتاج إلى فهم متوازن: ترك الترف لا يعني تحريم الحلال، والإنكار على الظلم لا يبرر التعدي، والعبادة لا تلغي حقوق الأسرة والمجتمع. لذلك نعرض العبرة الأخلاقية مع إحالة القارئ إلى النصوص لا إلى عبارات منسوبة بلا مصدر.', 'His ascetic character is presented with a balanced distinction between piety and unlawful extremism.', 'الزهد والصدق', 2)
ON CONFLICT (id) DO UPDATE SET
  companion_id = excluded.companion_id,
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  content_ar = excluded.content_ar,
  content_en = excluded.content_en,
  story_type = excluded.story_type,
  order_num = excluded.order_num,
  updated_at = now();
